<?php
declare (strict_types = 1);

namespace app\index\controller;

use app\common\model\NewsModel;
use app\common\model\NewsCategoryModel;
use think\facade\View;

class Author extends Common
{
	protected function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub


	}

	public function index()
    {
        $cid = input('cid',1);
        $map = [];
        if(!empty($cid)){
	        $categoryInfo = NewsCategoryModel::where('id',$cid)->find();
	        if($categoryInfo->pid===0){
	        	$categorySubIdArr = NewsCategoryModel::where('pid',$categoryInfo->id)->column('id');
	        	array_push($categorySubIdArr,$cid);
		        $map[] = ['category_id','in',$categorySubIdArr];
	        }else{
		        $map[] = ['category_id','=',$cid];
	        }

        }


	    $map[] = ['lang','=',$this->lang];
	    $map[] = ['status','=',1];
        $list = NewsModel::pageList($map,5);
        // 获取分页显示
        $page = $list->render();


	    $currentCategory = NewsCategoryModel::where('id',$cid)->find();
	    if($this->lang=='en'){
		    View::assign('currentCategoryName',$currentCategory->ename);
	    }else{
		    View::assign('currentCategoryName',$currentCategory->name);

	    }
	    View::assign('cid',$cid);


	    if(!empty($currentCategory->pid)){
		    $categoryPid = $currentCategory->pid;
	    }else{
		    $categoryPid = $currentCategory->id;

	    }
	    $currentCategoryList = NewsCategoryModel::where('pid',$categoryPid)->whereOr('id',$categoryPid)->order('sort','ASC')->select();
	    View::assign('currentCategoryList',$currentCategoryList);

        return view('author',['list'=>$list,'page'=>$page]);
    }

}
