<?php
declare (strict_types = 1);

namespace app\index\controller;

use app\common\model\NewsModel;
use app\common\model\NewsCategoryModel;
use think\facade\View;

class Author extends Common
{
	protected function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub


	}

	public function index()
    {
        $cid = input('cid',0);
        $map = [];
        if(!empty($cid)){
	        $categoryInfo = NewsCategoryModel::where('id',$cid)->find();
	        if($categoryInfo->pid===0){
	        	$categorySubIdArr = NewsCategoryModel::where('pid',$categoryInfo->id)->column('id');
	        	array_push($categorySubIdArr,$cid);
		        $map[] = ['category_id','in',$categorySubIdArr];
	        }else{
		        $map[] = ['category_id','=',$cid];
	        }

        }


	    $map[] = ['status','=',1];
        $list = NewsModel::pageList($map,10);
        // 获取分页显示
        $page = $list->render();
	    $count = $list->total();

	    $currentCategory = NewsCategoryModel::where('id',$cid)->find();
	    if(!empty($currentCategory)){
		    View::assign('currentCategoryName',$currentCategory->ename);
		    if(!empty($currentCategory->pid)){
			    $categoryPid = $currentCategory->pid;
		    }else{
			    $categoryPid = $currentCategory->id;
		    }
		    $currentCategoryList = NewsCategoryModel::where('pid',$categoryPid)->whereOr('id',$categoryPid)->order('sort','ASC')->select();
		    View::assign('currentCategoryList',$currentCategoryList);
	    }
	    View::assign('cid',$cid);






        return view('author',['list'=>$list,'page'=>$page,'count'=>$count]);
    }

}
