<?php
declare (strict_types = 1);

namespace app\api\controller;
use app\BaseController;
use think\console\Input;
use think\facade\Session;

class Common extends BaseController
{
    //protected $middleware = ['\app\middleware\Auth'];

	protected $comMap = [];

    protected function initialize()
    {
        //parent::initialize(); // TODO: Change the autogenerated stub


        $admin_id = Session::get('admin_id');
        if(empty($admin_id)){
            abort(1, '登录失效，请重新登录');
        }

        $lang = input('lang');
        if(!empty($lang)){
        	$this->comMap[] = ['lang','=',$lang];
        }
    }
}
