<?php
declare (strict_types = 1);

namespace app\api\controller;
use app\BaseController;

use think\facade\Db;
use app\api\model\MenuModel;
use app\common\model\AdminModel;

use think\captcha\facade\Captcha;
use think\facade\Session;


class Test extends Common
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        $admin_id = Session::get('admin_id');
        print_r($admin_id);
    }
}
